### PR TITLE
Add toggle function (bad but works)

### PR DESCRIPTION
**Pull request by Khristian-kun**

### CODE REVIEW

**Comment by TrinityDevelopers** [comment]
I don't want to commit this because this code is not that dynamic.  We are working on another solution.  Thanks for the contribution though! :)

**Comment by Khristian-kun** [comment]
ok, ill wait for it :)

**Comment by TrinityDevelopers** [comment]
Ok I added another solution.  Closing this.

**Comment by Khristian-kun** [comment]
ok

**Pull request closed without merging**
